Repository brave/browser-android-tabs, pull requests merged in 2019-07, with the labels that each got.

#1792 Skip adblock check for sync lib requests
  chrome/browser/net/blockers/blockers_worker.cc
  chrome/browser/net/blockers/blockers_worker.h
  chrome/browser/net/chrome_network_delegate.cc
Labels: QA/Yes, feature/shields, feature/sync

#1845 Fix turning on Brave Ads will cause some websites to display the “something went wrong” error message
  components/dom_distiller/content/browser/distiller_page_web_contents.cc
Labels: bug, priority/P1

#1852 Release notes for Brave 1.1.1
  CHANGELOG.md
Labels: release-notes, release-notes/exclude

#1877 Fixes deep settings navigation (Rewards)
  package-lock.json
  package.json
Labels: bug/BR

#1892 C76 Client Side updates
  components/brave_rewards_ui/resources/actions/rewards_actions.ts
  components/brave_rewards_ui/resources/brave_rewards.tsx
  components/brave_rewards_ui/resources/components/adsBox.tsx
  components/brave_rewards_ui/resources/components/app.tsx
  components/brave_rewards_ui/resources/components/contributeBox.tsx
  components/brave_rewards_ui/resources/components/donationsBox.tsx
  components/brave_rewards_ui/resources/components/pageWallet.tsx
  components/brave_rewards_ui/resources/components/settingsPage.tsx
  components/brave_rewards_ui/resources/constants/rewards_types.ts
  components/brave_rewards_ui/resources/reducers/grant_reducer.ts
  components/brave_rewards_ui/resources/reducers/publishers_reducer.ts
  components/brave_rewards_ui/resources/reducers/rewards_reducer.ts
  components/brave_rewards_ui/resources/reducers/wallet_reducer.ts
  components/brave_rewards_ui/resources/storage.ts
  components/definitions/rewards.d.ts
Labels: feature/BR
