Repository brave/browser-android-tabs, pull requests merged in 2020-01, with the labels that each got.

#2413 Check getActivityTab() result for null; fixes browser-android-tabs#2412
  chrome/android/java/src/org/chromium/chrome/browser/ChromeTabbedActivity.java
Labels: crash

#2335 fix verified icon flashes. Issue# 2328
  chrome/android/java/src/org/chromium/chrome/browser/toolbar/top/ToolbarPhone.java
  chrome/android/java/src/org/chromium/chrome/browser/toolbar/top/ToolbarTablet.java
Labels: ARM, bug/UX, bug/rewards

#2450 Convert punycode to unicode on native UI. Issue# 2289
  chrome/android/java/src/org/chromium/chrome/browser/BraveRewardsDonationSentActivity.java
  chrome/android/java/src/org/chromium/chrome/browser/BraveRewardsPanelPopup.java
  chrome/android/java/src/org/chromium/chrome/browser/BraveRewardsSiteBannerActivity.java
Labels: QA/Yes, bug/UX

#2486 Claim multiple grants from the panel. Issue# 7763
  chrome/android/java/src/org/chromium/chrome/browser/BraveRewardsNativeWorker.java
  chrome/android/java/src/org/chromium/chrome/browser/BraveRewardsObserver.java
  chrome/android/java/src/org/chromium/chrome/browser/BraveRewardsPanelPopup.java
Labels: bug/UX

#2449 Handling new rewards notifications. Issue# 2198
  chrome/android/java/res/layout/brave_rewards_panel_grant.xml
  chrome/android/java/src/org/chromium/chrome/browser/BraveRewardsNativeWorker.java
  chrome/android/java/src/org/chromium/chrome/browser/BraveRewardsPanelPopup.java
  chrome/android/java/strings/android_chrome_strings.grd
  chrome/android/java/strings/strings.xml
Labels: feature/rewards

#2480 If sent from the background, the ads notifications should not make sound and pop up on the screen.Issue #2419.
  chrome/android/java/src/org/chromium/chrome/browser/notifications/BraveAds.java
  chrome/android/java/src/org/chromium/chrome/browser/notifications/BraveAdsNotificationBuilder.java
  chrome/android/java/src/org/chromium/chrome/browser/notifications/channels/ChannelDefinitions.java
  chrome/android/java/strings/android_chrome_strings.grd
  chrome/android/java/strings/strings.xml
Labels: QA/Yes
