Repository brave/browser-android-tabs, pull requests merged in 2020-02, with the labels that each got.

#2506 Proper object_id when deleting from level db
  chrome/browser/brave_sync_worker.cc
Labels: crash, feature/sync

#2545 Crash when ad notification is shown.
  chrome/android/java/src/org/chromium/chrome/browser/notifications/NotificationPlatformBridge.java
Labels: QA/Yes, bug

#2571 CHANGELOG relesae notes for 1.5.5 & 1.5.6
  CHANGELOG.md
Labels: QA/No, release-notes/exclude
